version = 1

test_patterns = ["test/*.e2e-spec.ts"]

exclude_patterns = [
  "node_modules/**",
  "dist/**",
  ".github/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "mongo",
    "jest"
  ]